### ISSUE TITLE
Should integrate this into verify-frontend?

### ISSUE THREAD

**Issue by robinwhittleton** [richardTowers/mock-verify-hub#1]
We already include sinatra into verify-frontend for stubbing analytics endpoints. Should we directly integrate these endpoint stubs too?

**Comment by robinwhittleton** [comment]
Potentially solved by https://github.com/alphagov/verify-frontend/pull/178

**Comment by richardTowers** [comment]
Ha, coincidence, I didn't actually see this until today. But yeah, this would be fixed by alphagov/verify-frontend#178.

If people are happy with that I'll deprecate this repo once it's merged.

**Comment by richardTowers** [comment]
Closed by #178
